spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8080

jwt:
  secret: dev-secret-key-minimum-256-bits-for-hs256-algorithm-change-in-production

cors:
  allowed-origins: http://localhost:3000,http://localhost:4000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

redis:
  host: localhost
  port: 6379
  password: ""

logging:
  level:
    com.snapservice: DEBUG
    org.springframework.cloud.gateway: DEBUG

# spring:
#   cloud:
#     discovery:
#       locator:
#         enabled: false
#     gateway:
#       server:
#         webmvc:
#           routes:
#             - id: seeker-service
#               uri: lb://seeker-service
#               predicates:
#                 - Path=/api/v1/seeker/**
#             - id: provider-service
#               uri: lb://provider-service
#               predicates:
#                 - Path=/api/v1/provider/**
#             - id: admin-service
#               uri: lb://admin-service
#               predicates:
#                 - Path=/api/v1/admin/**
#             - id: auth-service
#               uri: lb://auth-service
#               predicates:
#                 - Path=/api/v1/auth/**
#             - id: notification-service
#               uri: lb://notification-service
#               predicates:
#                 - Path=/api/v1/notification/**
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
#   instance:
#     prefer-ip-address: true
#     lease-expiration-duration-in-seconds: 90
#     lease-renewal-interval-in-seconds: 30