server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${AUTH_DB_NAME:auth_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_USERPASSWORD:postgres123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # redis:
  #   host: prod-redis-host
  #   port: 6379
  #   password: '{cipher}PROD_REDIS_PASSWORD'
  #   timeout: 60000ms
    
  # kafka:
  #   bootstrap-servers: prod-kafka-broker:9092
  #   consumer:
  #     group-id: auth-service
  #     auto-offset-reset: earliest
  #   producer:
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: '{cipher}PROD_JWT_SECRET'
  expiration: 86400000
  refresh-expiration: 604800000

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
  # apple:
  #   client-id: ${APPLE_CLIENT_ID}
  #   client-secret: '{cipher}PROD_APPLE_SECRET'

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}

logging:
  level:
    root: WARN
    com.snapservice: INFO