spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8081

jwt:
  secret: vD1z2kJt5sJ4yKzFq3W9pR1mT7xB2nU6gC8hE0aQ9vM4yT5pL7rD3zN1wH2uX5yV
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days

app:
  frontend:
    url: http://localhost:3000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: Postgres123
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: tabarishadow@gmail.com
    password: tsrd wtmb urma zfmz

logging:
  level:
    com.proximityfinder: DEBUG
    org.hibernate.SQL: DEBUG